### ISSUE TITLE
Remove CodeMirror 2 support

### ISSUE THREAD

**Issue by le717** [DennisKehrig/brackets-show-whitespace#28]
Brackets has been using CodeMirror 4.x since May 2014, the minimum supported Brackets version (sprint 31) is from September 2013, and we are now on release 1.1. Any CodeMirror 2 code is no longer applicable, and thus should be dropped and the minimum version raised to sprint 38.

**Comment by DennisKehrig** [comment]
Hey @le717, thanks for suggesting this.

I'm wondering, is there any problem with supporting older versions? I don't know whether there are people using older versions of Brackets for some compatibility reasons - wild speculation here - who would like to otherwise use newer versions of plugins where possible.

But if this legacy code makes new feature harder to implement, I'm all for it.

What are your reasons?

**Comment by le717** [comment]
@DennisKehrig Yes, there are some conflicts with legacy CM2 code and new features. Specifically, on new releases CM2 stuff never runs. And the older versions may not support the items required for the new features (example: #30 requires 0.41+ for the `themes` preference). So keeping the legacy code can mean not being able to implement new features. (I am pretty sure) this extension needs updating to the new events system, and that is 1.1+ and certainly does not work in older Brackets versions.

Also, if it helps you decide, the Extension Manager keeps tracks of older versions and allows people running older Brackets to download the newest supported version.
